name: Regression suite

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest -s --html=reports.html --self-contained-html
    
    - name: Upload report
      uses: actions/upload-artifact@v1
      with: 
        name: pytest-report
        path: report.html
